/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import jpanelimage.ImagenFondo;
import jpanelimage.JPanelImage;
import noticias.Principal;

/**
 *
 * @author Adrián
 */
public class Tienda extends javax.swing.JFrame {
    
    // Mover posicion
    private boolean moving = false;
    private Point start;
    
    // Busqueda
    private String busqueda;
    private int orderBy;
    private int limit = 10;
    private int categoria = 0;
    
    private List<Producto> listaProductos;
    private HashMap<Producto, Integer> productos;
    private JPanel[] listeners;
    
    private Producto productSelected;
    
    private Principal noticias;
    private boolean cerrar;
    
    private double monedero=50;

    
    
    /**
     * Creates new form Principal
     */
    public Tienda(Principal noticias) {
        this.setUndecorated(true);
        
        initComponents();
        
        
        this.noticias = noticias;
        productos = new HashMap<>();
        
        listeners = new JPanel[] {
            producto1,producto2,producto3,producto4,producto5,producto6,producto7,producto8,producto9,producto10
        };
        
        mostrarProductosLista();
        
        // Ponemos el fondo de pantalla
        fondoPantalla.setImagenFondo(new ImagenFondo(new File("./imagenes/fondoTienda.jpg"), 1f));
        iconoCartera.setImagenFondo(new ImagenFondo(new File("./imagenes/iconoMonedero.png"), 1f));
        iconoCarrito.setImagenFondo(new ImagenFondo(new File("./imagenes/iconoCarrito.png"), 1f));
        
        // Configuramos que hacer cuando se cierre
        this.setSize(960, 640);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        cerrar=true;
        this.setLocationRelativeTo(null);
        
        comboOrden.setForeground(new Color(0,0,0));
        comboOrden.setBackground(new Color(255,255,255,1));
        comboOrden.getEditor().getEditorComponent().setBackground(new Color(0,0,0,0));
        
        botonAdd.setBackground(new Color(0,40,60,1));
        botonFinalizar.setBackground(new Color(0,40,60,1));
        botonBuscar.setBackground(new Color(0,40,60,1));
        
        buscador.setBackground(new Color(0,0,0,0));
        
        scroll.getViewport().setBackground(new Color(0,0,0,0));
        scroll.setViewportBorder(null);
        
        scroll2.getViewport().setBackground(new Color(0,0,0,0));
        scroll2.setViewportBorder(null);
        
        valorMonedero.setText((new DecimalFormat("0.00").format(monedero)+"€"));
        
        reiniciarContenido();
        
        new Thread (new Runnable() {
            @Override
            public void run() {
                while(true) {
                    repaint();
                    try {
                        Thread.sleep(100L);
                    } catch (InterruptedException ex) {
                        System.out.println("ERROR: "+ex);
                    }
                }
                
            }
        }).start();
    }
    
    public void setOnDispose (){
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        cerrar=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPantalla = new jpanelimage.JPanelImage();
        panelCategorias = new javax.swing.JPanel();
        panelBuscador = new javax.swing.JPanel();
        buscador = new javax.swing.JTextField();
        comboOrden = new javax.swing.JComboBox<>();
        botonBuscar = new javax.swing.JButton();
        panelProducto = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        producto1 = new javax.swing.JPanel();
        jPanelImage6 = new jpanelimage.JPanelImage();
        categoriaTodas6 = new javax.swing.JLabel();
        categoriaTodas7 = new javax.swing.JLabel();
        puntuacion1 = new javax.swing.JLabel();
        producto2 = new javax.swing.JPanel();
        jPanelImage7 = new jpanelimage.JPanelImage();
        categoriaTodas8 = new javax.swing.JLabel();
        categoriaTodas9 = new javax.swing.JLabel();
        puntuacion2 = new javax.swing.JLabel();
        producto3 = new javax.swing.JPanel();
        jPanelImage8 = new jpanelimage.JPanelImage();
        categoriaTodas10 = new javax.swing.JLabel();
        categoriaTodas11 = new javax.swing.JLabel();
        puntuacion3 = new javax.swing.JLabel();
        producto4 = new javax.swing.JPanel();
        jPanelImage9 = new jpanelimage.JPanelImage();
        categoriaTodas12 = new javax.swing.JLabel();
        categoriaTodas13 = new javax.swing.JLabel();
        puntuacion4 = new javax.swing.JLabel();
        producto5 = new javax.swing.JPanel();
        jPanelImage10 = new jpanelimage.JPanelImage();
        categoriaTodas14 = new javax.swing.JLabel();
        categoriaTodas15 = new javax.swing.JLabel();
        puntuacion5 = new javax.swing.JLabel();
        producto6 = new javax.swing.JPanel();
        jPanelImage11 = new jpanelimage.JPanelImage();
        categoriaTodas16 = new javax.swing.JLabel();
        categoriaTodas17 = new javax.swing.JLabel();
        puntuacion6 = new javax.swing.JLabel();
        producto7 = new javax.swing.JPanel();
        jPanelImage12 = new jpanelimage.JPanelImage();
        categoriaTodas18 = new javax.swing.JLabel();
        categoriaTodas19 = new javax.swing.JLabel();
        puntuacion7 = new javax.swing.JLabel();
        producto8 = new javax.swing.JPanel();
        jPanelImage13 = new jpanelimage.JPanelImage();
        categoriaTodas20 = new javax.swing.JLabel();
        categoriaTodas21 = new javax.swing.JLabel();
        puntuacion8 = new javax.swing.JLabel();
        producto9 = new javax.swing.JPanel();
        jPanelImage14 = new jpanelimage.JPanelImage();
        categoriaTodas22 = new javax.swing.JLabel();
        categoriaTodas23 = new javax.swing.JLabel();
        puntuacion9 = new javax.swing.JLabel();
        producto10 = new javax.swing.JPanel();
        jPanelImage15 = new jpanelimage.JPanelImage();
        categoriaTodas24 = new javax.swing.JLabel();
        categoriaTodas25 = new javax.swing.JLabel();
        puntuacion10 = new javax.swing.JLabel();
        valorCarrito = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        categoriaTodas1 = new javax.swing.JLabel();
        iconoCartera = new jpanelimage.JPanelImage();
        iconoCarrito = new jpanelimage.JPanelImage();
        valorMonedero = new javax.swing.JLabel();
        botonFinalizar = new javax.swing.JButton();
        panelContenido = new javax.swing.JPanel();
        panelBarra = new javax.swing.JPanel();
        minimizar = new javax.swing.JLabel();
        equis = new javax.swing.JLabel();
        scroll2 = new javax.swing.JScrollPane();
        panelContenidoFondo = new javax.swing.JPanel();
        img3 = new jpanelimage.JPanelImage();
        img1 = new jpanelimage.JPanelImage();
        img2 = new jpanelimage.JPanelImage();
        puntuacionContenido = new javax.swing.JLabel();
        tituloContenido = new javax.swing.JLabel();
        textoContenido = new javax.swing.JLabel();
        precioContenido = new javax.swing.JLabel();
        botonAdd = new javax.swing.JButton();
        panelPrecio = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoPantalla.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));
        fondoPantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCategorias.setBackground(new java.awt.Color(0, 102, 51));
        panelCategorias.setOpaque(false);

        javax.swing.GroupLayout panelCategoriasLayout = new javax.swing.GroupLayout(panelCategorias);
        panelCategorias.setLayout(panelCategoriasLayout);
        panelCategoriasLayout.setHorizontalGroup(
            panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelCategoriasLayout.setVerticalGroup(
            panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        fondoPantalla.add(panelCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 640));

        panelBuscador.setBackground(new java.awt.Color(0, 255, 153));
        panelBuscador.setOpaque(false);
        panelBuscador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscador.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        buscador.setForeground(new java.awt.Color(255, 255, 255));
        buscador.setText("Buscar...");
        buscador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 2));
        buscador.setOpaque(false);
        panelBuscador.add(buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 153, 28));

        comboOrden.setBackground(new java.awt.Color(255, 153, 102));
        comboOrden.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        comboOrden.setForeground(new java.awt.Color(255, 255, 255));
        comboOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alfabetico", "Precio", "Puntuación", "Fecha" }));
        comboOrden.setBorder(null);
        comboOrden.setOpaque(false);
        comboOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOrdenActionPerformed(evt);
            }
        });
        panelBuscador.add(comboOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 111, 28));

        botonBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscar.setText("Buscar");
        botonBuscar.setBorder(null);
        botonBuscar.setOpaque(false);
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        panelBuscador.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 70, 30));

        fondoPantalla.add(panelBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 370, 50));

        panelProducto.setBackground(new java.awt.Color(102, 255, 102));
        panelProducto.setOpaque(false);
        panelProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scroll.setBorder(null);
        scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        producto1.setBackground(new java.awt.Color(255, 255, 51));
        producto1.setOpaque(false);
        producto1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelImage6.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));
        jPanelImage6.setName("imagen"); // NOI18N

        javax.swing.GroupLayout jPanelImage6Layout = new javax.swing.GroupLayout(jPanelImage6);
        jPanelImage6.setLayout(jPanelImage6Layout);
        jPanelImage6Layout.setHorizontalGroup(
            jPanelImage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelImage6Layout.setVerticalGroup(
            jPanelImage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        producto1.add(jPanelImage6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanelImage6.getAccessibleContext().setAccessibleName("imagen");

        categoriaTodas6.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        categoriaTodas6.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoriaTodas6.setText("<html>Bicicleta Mercurio Superbronco Rodada...</html>");
        categoriaTodas6.setName("titulo"); // NOI18N
        producto1.add(categoriaTodas6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 120, 50));
        categoriaTodas6.getAccessibleContext().setAccessibleName("titulo");

        categoriaTodas7.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        categoriaTodas7.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoriaTodas7.setText("2999,99€");
        categoriaTodas7.setName("precio"); // NOI18N
        producto1.add(categoriaTodas7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 70, 20));
        categoriaTodas7.getAccessibleContext().setAccessibleName("precio");

        puntuacion1.setBackground(new java.awt.Color(0, 104, 52));
        puntuacion1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        puntuacion1.setForeground(new java.awt.Color(255, 255, 255));
        puntuacion1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        puntuacion1.setText("<html>★★★★</html>");
        puntuacion1.setName("puntuacion"); // NOI18N
        producto1.add(puntuacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));
        puntuacion1.getAccessibleContext().setAccessibleName("puntuacion");

        jPanel3.add(producto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 100));

        producto2.setBackground(new java.awt.Color(255, 255, 51));
        producto2.setOpaque(false);
        producto2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelImage7.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));
        jPanelImage7.setName("imagen"); // NOI18N

        javax.swing.GroupLayout jPanelImage7Layout = new javax.swing.GroupLayout(jPanelImage7);
        jPanelImage7.setLayout(jPanelImage7Layout);
        jPanelImage7Layout.setHorizontalGroup(
            jPanelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelImage7Layout.setVerticalGroup(
            jPanelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        producto2.add(jPanelImage7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        categoriaTodas8.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        categoriaTodas8.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoriaTodas8.setText("<html>Bicicleta Mercurio Superbronco Rodada...</html>");
        categoriaTodas8.setName("titulo"); // NOI18N
        producto2.add(categoriaTodas8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 120, 50));

        categoriaTodas9.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        categoriaTodas9.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoriaTodas9.setText("2999,99€");
        categoriaTodas9.setName("precio"); // NOI18N
        producto2.add(categoriaTodas9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 70, 20));

        puntuacion2.setBackground(new java.awt.Color(0, 104, 52));
        puntuacion2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        puntuacion2.setForeground(new java.awt.Color(255, 255, 255));
        puntuacion2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        puntuacion2.setText("<html>★★★★</html>");
        puntuacion2.setName("puntuacion"); // NOI18N
        producto2.add(puntuacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));

        jPanel3.add(producto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 250, 100));

        producto3.setBackground(new java.awt.Color(255, 255, 51));
        producto3.setOpaque(false);
        producto3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelImage8.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));
        jPanelImage8.setName("imagen"); // NOI18N

        javax.swing.GroupLayout jPanelImage8Layout = new javax.swing.GroupLayout(jPanelImage8);
        jPanelImage8.setLayout(jPanelImage8Layout);
        jPanelImage8Layout.setHorizontalGroup(
            jPanelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelImage8Layout.setVerticalGroup(
            jPanelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        producto3.add(jPanelImage8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        categoriaTodas10.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        categoriaTodas10.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoriaTodas10.setText("<html>Bicicleta Mercurio Superbronco Rodada...</html>");
        categoriaTodas10.setName("titulo"); // NOI18N
        producto3.add(categoriaTodas10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 120, 50));

        categoriaTodas11.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        categoriaTodas11.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoriaTodas11.setText("2999,99€");
        categoriaTodas11.setName("precio"); // NOI18N
        producto3.add(categoriaTodas11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 70, 20));

        puntuacion3.setBackground(new java.awt.Color(0, 104, 52));
        puntuacion3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        puntuacion3.setForeground(new java.awt.Color(255, 255, 255));
        puntuacion3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        puntuacion3.setText("<html>★★★★</html>");
        puntuacion3.setName("puntuacion"); // NOI18N
        producto3.add(puntuacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));

        jPanel3.add(producto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 250, 100));

        producto4.setBackground(new java.awt.Color(255, 255, 51));
        producto4.setOpaque(false);
        producto4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelImage9.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));
        jPanelImage9.setName("imagen"); // NOI18N

        javax.swing.GroupLayout jPanelImage9Layout = new javax.swing.GroupLayout(jPanelImage9);
        jPanelImage9.setLayout(jPanelImage9Layout);
        jPanelImage9Layout.setHorizontalGroup(
            jPanelImage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelImage9Layout.setVerticalGroup(
            jPanelImage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        producto4.add(jPanelImage9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        categoriaTodas12.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        categoriaTodas12.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoriaTodas12.setText("<html>Bicicleta Mercurio Superbronco Rodada...</html>");
        categoriaTodas12.setName("titulo"); // NOI18N
        producto4.add(categoriaTodas12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 120, 50));

        categoriaTodas13.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        categoriaTodas13.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoriaTodas13.setText("2999,99€");
        categoriaTodas13.setName("precio"); // NOI18N
        producto4.add(categoriaTodas13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 70, 20));

        puntuacion4.setBackground(new java.awt.Color(0, 104, 52));
        puntuacion4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        puntuacion4.setForeground(new java.awt.Color(255, 255, 255));
        puntuacion4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        puntuacion4.setText("<html>★★★★</html>");
        puntuacion4.setName("puntuacion"); // NOI18N
        producto4.add(puntuacion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));

        jPanel3.add(producto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 250, 100));

        producto5.setBackground(new java.awt.Color(255, 255, 51));
        producto5.setOpaque(false);
        producto5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelImage10.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));
        jPanelImage10.setName("imagen"); // NOI18N

        javax.swing.GroupLayout jPanelImage10Layout = new javax.swing.GroupLayout(jPanelImage10);
        jPanelImage10.setLayout(jPanelImage10Layout);
        jPanelImage10Layout.setHorizontalGroup(
            jPanelImage10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelImage10Layout.setVerticalGroup(
            jPanelImage10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        producto5.add(jPanelImage10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        categoriaTodas14.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        categoriaTodas14.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoriaTodas14.setText("<html>Bicicleta Mercurio Superbronco Rodada...</html>");
        categoriaTodas14.setName("titulo"); // NOI18N
        producto5.add(categoriaTodas14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 120, 50));

        categoriaTodas15.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        categoriaTodas15.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoriaTodas15.setText("2999,99€");
        categoriaTodas15.setName("precio"); // NOI18N
        producto5.add(categoriaTodas15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 70, 20));

        puntuacion5.setBackground(new java.awt.Color(0, 104, 52));
        puntuacion5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        puntuacion5.setForeground(new java.awt.Color(255, 255, 255));
        puntuacion5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        puntuacion5.setText("<html>★★★★</html>");
        puntuacion5.setName("puntuacion"); // NOI18N
        producto5.add(puntuacion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));

        jPanel3.add(producto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 250, 100));

        producto6.setBackground(new java.awt.Color(255, 255, 51));
        producto6.setOpaque(false);
        producto6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelImage11.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));
        jPanelImage11.setName("imagen"); // NOI18N

        javax.swing.GroupLayout jPanelImage11Layout = new javax.swing.GroupLayout(jPanelImage11);
        jPanelImage11.setLayout(jPanelImage11Layout);
        jPanelImage11Layout.setHorizontalGroup(
            jPanelImage11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelImage11Layout.setVerticalGroup(
            jPanelImage11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        producto6.add(jPanelImage11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        categoriaTodas16.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        categoriaTodas16.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoriaTodas16.setText("<html>Bicicleta Mercurio Superbronco Rodada...</html>");
        categoriaTodas16.setName("titulo"); // NOI18N
        producto6.add(categoriaTodas16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 120, 50));

        categoriaTodas17.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        categoriaTodas17.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoriaTodas17.setText("2999,99€");
        categoriaTodas17.setName("precio"); // NOI18N
        producto6.add(categoriaTodas17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 70, 20));

        puntuacion6.setBackground(new java.awt.Color(0, 104, 52));
        puntuacion6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        puntuacion6.setForeground(new java.awt.Color(255, 255, 255));
        puntuacion6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        puntuacion6.setText("<html>★★★★</html>");
        puntuacion6.setName("puntuacion"); // NOI18N
        producto6.add(puntuacion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));

        jPanel3.add(producto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 250, 100));

        producto7.setBackground(new java.awt.Color(255, 255, 51));
        producto7.setOpaque(false);
        producto7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelImage12.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));
        jPanelImage12.setName("imagen"); // NOI18N

        javax.swing.GroupLayout jPanelImage12Layout = new javax.swing.GroupLayout(jPanelImage12);
        jPanelImage12.setLayout(jPanelImage12Layout);
        jPanelImage12Layout.setHorizontalGroup(
            jPanelImage12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelImage12Layout.setVerticalGroup(
            jPanelImage12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        producto7.add(jPanelImage12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        categoriaTodas18.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        categoriaTodas18.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoriaTodas18.setText("<html>Bicicleta Mercurio Superbronco Rodada...</html>");
        categoriaTodas18.setName("titulo"); // NOI18N
        producto7.add(categoriaTodas18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 120, 50));

        categoriaTodas19.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        categoriaTodas19.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoriaTodas19.setText("2999,99€");
        categoriaTodas19.setName("precio"); // NOI18N
        producto7.add(categoriaTodas19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 70, 20));

        puntuacion7.setBackground(new java.awt.Color(0, 104, 52));
        puntuacion7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        puntuacion7.setForeground(new java.awt.Color(255, 255, 255));
        puntuacion7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        puntuacion7.setText("<html>★★★★</html>");
        puntuacion7.setName("puntuacion"); // NOI18N
        producto7.add(puntuacion7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));

        jPanel3.add(producto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 250, 100));

        producto8.setBackground(new java.awt.Color(255, 255, 51));
        producto8.setOpaque(false);
        producto8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelImage13.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));
        jPanelImage13.setName("imagen"); // NOI18N

        javax.swing.GroupLayout jPanelImage13Layout = new javax.swing.GroupLayout(jPanelImage13);
        jPanelImage13.setLayout(jPanelImage13Layout);
        jPanelImage13Layout.setHorizontalGroup(
            jPanelImage13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelImage13Layout.setVerticalGroup(
            jPanelImage13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        producto8.add(jPanelImage13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        categoriaTodas20.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        categoriaTodas20.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoriaTodas20.setText("<html>Bicicleta Mercurio Superbronco Rodada...</html>");
        categoriaTodas20.setName("titulo"); // NOI18N
        producto8.add(categoriaTodas20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 120, 50));

        categoriaTodas21.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        categoriaTodas21.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoriaTodas21.setText("2999,99€");
        categoriaTodas21.setName("precio"); // NOI18N
        producto8.add(categoriaTodas21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 70, 20));

        puntuacion8.setBackground(new java.awt.Color(0, 104, 52));
        puntuacion8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        puntuacion8.setForeground(new java.awt.Color(255, 255, 255));
        puntuacion8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        puntuacion8.setText("<html>★★★★</html>");
        puntuacion8.setName("puntuacion"); // NOI18N
        producto8.add(puntuacion8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));

        jPanel3.add(producto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 780, 250, 100));

        producto9.setBackground(new java.awt.Color(255, 255, 51));
        producto9.setOpaque(false);
        producto9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelImage14.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));
        jPanelImage14.setName("imagen"); // NOI18N

        javax.swing.GroupLayout jPanelImage14Layout = new javax.swing.GroupLayout(jPanelImage14);
        jPanelImage14.setLayout(jPanelImage14Layout);
        jPanelImage14Layout.setHorizontalGroup(
            jPanelImage14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelImage14Layout.setVerticalGroup(
            jPanelImage14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        producto9.add(jPanelImage14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        categoriaTodas22.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        categoriaTodas22.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoriaTodas22.setText("<html>Bicicleta Mercurio Superbronco Rodada...</html>");
        categoriaTodas22.setName("titulo"); // NOI18N
        producto9.add(categoriaTodas22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 120, 50));

        categoriaTodas23.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        categoriaTodas23.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoriaTodas23.setText("2999,99€");
        categoriaTodas23.setName("precio"); // NOI18N
        producto9.add(categoriaTodas23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 70, 20));

        puntuacion9.setBackground(new java.awt.Color(0, 104, 52));
        puntuacion9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        puntuacion9.setForeground(new java.awt.Color(255, 255, 255));
        puntuacion9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        puntuacion9.setText("<html>★★★★</html>");
        puntuacion9.setName("puntuacion"); // NOI18N
        producto9.add(puntuacion9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));

        jPanel3.add(producto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 890, 250, 100));

        producto10.setBackground(new java.awt.Color(255, 255, 51));
        producto10.setOpaque(false);
        producto10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelImage15.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));
        jPanelImage15.setName("imagen"); // NOI18N

        javax.swing.GroupLayout jPanelImage15Layout = new javax.swing.GroupLayout(jPanelImage15);
        jPanelImage15.setLayout(jPanelImage15Layout);
        jPanelImage15Layout.setHorizontalGroup(
            jPanelImage15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelImage15Layout.setVerticalGroup(
            jPanelImage15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        producto10.add(jPanelImage15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        categoriaTodas24.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        categoriaTodas24.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoriaTodas24.setText("<html>Bicicleta Mercurio Superbronco Rodada...</html>");
        categoriaTodas24.setName("titulo"); // NOI18N
        producto10.add(categoriaTodas24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 120, 50));

        categoriaTodas25.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        categoriaTodas25.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoriaTodas25.setText("2999,99€");
        categoriaTodas25.setName("precio"); // NOI18N
        producto10.add(categoriaTodas25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 70, 20));

        puntuacion10.setBackground(new java.awt.Color(0, 104, 52));
        puntuacion10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        puntuacion10.setForeground(new java.awt.Color(255, 255, 255));
        puntuacion10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        puntuacion10.setText("<html>★★★★</html>");
        puntuacion10.setName("puntuacion"); // NOI18N
        producto10.add(puntuacion10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));

        jPanel3.add(producto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1000, 250, 100));

        scroll.setViewportView(jPanel3);

        panelProducto.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 290, 420));

        valorCarrito.setBackground(new java.awt.Color(0, 104, 52));
        valorCarrito.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        valorCarrito.setForeground(new java.awt.Color(255, 255, 255));
        valorCarrito.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        valorCarrito.setText("0.00€");
        panelProducto.add(valorCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 60, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        panelProducto.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 270, 1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        panelProducto.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 270, 1));

        categoriaTodas1.setBackground(new java.awt.Color(0, 104, 52));
        categoriaTodas1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        categoriaTodas1.setForeground(new java.awt.Color(255, 255, 255));
        categoriaTodas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoriaTodas1.setText("PRODUCTOS");
        categoriaTodas1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelProducto.add(categoriaTodas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 250, 30));

        iconoCartera.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));

        javax.swing.GroupLayout iconoCarteraLayout = new javax.swing.GroupLayout(iconoCartera);
        iconoCartera.setLayout(iconoCarteraLayout);
        iconoCarteraLayout.setHorizontalGroup(
            iconoCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        iconoCarteraLayout.setVerticalGroup(
            iconoCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panelProducto.add(iconoCartera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 40, 40));

        iconoCarrito.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));

        javax.swing.GroupLayout iconoCarritoLayout = new javax.swing.GroupLayout(iconoCarrito);
        iconoCarrito.setLayout(iconoCarritoLayout);
        iconoCarritoLayout.setHorizontalGroup(
            iconoCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        iconoCarritoLayout.setVerticalGroup(
            iconoCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panelProducto.add(iconoCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 40, 40));

        valorMonedero.setBackground(new java.awt.Color(0, 104, 52));
        valorMonedero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        valorMonedero.setForeground(new java.awt.Color(255, 255, 255));
        valorMonedero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        valorMonedero.setText("50.00€");
        panelProducto.add(valorMonedero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 60, 40));

        botonFinalizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        botonFinalizar.setText("Finalizar compra");
        botonFinalizar.setBorder(null);
        botonFinalizar.setOpaque(false);
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });
        panelProducto.add(botonFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 200, 40));

        fondoPantalla.add(panelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 290, 590));

        panelContenido.setBackground(new java.awt.Color(204, 255, 204));
        panelContenido.setOpaque(false);
        panelContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarra.setBackground(new java.awt.Color(0, 51, 153));
        panelBarra.setOpaque(false);
        panelBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBarraMouseDragged(evt);
            }
        });
        panelBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelBarraMouseReleased(evt);
            }
        });
        panelBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        minimizar.setForeground(new java.awt.Color(255, 255, 255));
        minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizar.setText("_");
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        panelBarra.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 40, 39));

        equis.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        equis.setForeground(new java.awt.Color(255, 255, 255));
        equis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equis.setText("x");
        equis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equisMouseClicked(evt);
            }
        });
        panelBarra.add(equis, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 40, 39));

        panelContenido.add(panelBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 60));

        scroll2.setBorder(null);
        scroll2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panelContenidoFondo.setBackground(new java.awt.Color(153, 255, 153));
        panelContenidoFondo.setMinimumSize(new java.awt.Dimension(580, 400));
        panelContenidoFondo.setOpaque(false);
        panelContenidoFondo.setPreferredSize(new java.awt.Dimension(603, 300));
        panelContenidoFondo.setRequestFocusEnabled(false);
        panelContenidoFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img3.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));

        javax.swing.GroupLayout img3Layout = new javax.swing.GroupLayout(img3);
        img3.setLayout(img3Layout);
        img3Layout.setHorizontalGroup(
            img3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        img3Layout.setVerticalGroup(
            img3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        panelContenidoFondo.add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 190, 130));

        img1.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));

        javax.swing.GroupLayout img1Layout = new javax.swing.GroupLayout(img1);
        img1.setLayout(img1Layout);
        img1Layout.setHorizontalGroup(
            img1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        img1Layout.setVerticalGroup(
            img1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        panelContenidoFondo.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 280));

        img2.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));

        javax.swing.GroupLayout img2Layout = new javax.swing.GroupLayout(img2);
        img2.setLayout(img2Layout);
        img2Layout.setHorizontalGroup(
            img2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        img2Layout.setVerticalGroup(
            img2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        panelContenidoFondo.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 190, 140));

        puntuacionContenido.setBackground(new java.awt.Color(0, 104, 52));
        puntuacionContenido.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        puntuacionContenido.setForeground(new java.awt.Color(255, 255, 255));
        puntuacionContenido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        puntuacionContenido.setText("<html>XXXXX</html>");
        panelContenidoFondo.add(puntuacionContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 130, 40));
        puntuacionContenido.getAccessibleContext().setAccessibleName("");

        tituloContenido.setBackground(new java.awt.Color(0, 104, 52));
        tituloContenido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tituloContenido.setForeground(new java.awt.Color(255, 255, 255));
        tituloContenido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloContenido.setText("<html><h2>Bicicleta Mercurio Superbronco Rodada 20 Bmx Cross 2018</h2></html>");
        panelContenidoFondo.add(tituloContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 540, 50));

        textoContenido.setBackground(new java.awt.Color(0, 104, 52));
        textoContenido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textoContenido.setForeground(new java.awt.Color(255, 255, 255));
        textoContenido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoContenido.setText("<html>\n<pre>\nRodada 20\n1 velocidad\nFrenos en U\nRines de aluminio con 48 barrenos\nSistema de rotor\nCadena tipo moto\nAccesorios VITAL\nColores: Negro mate, Naranja metalico y Magenta metalico\n\n\nIMPORTANTE SOBRE LA FACTURACIÓN\nSi requieres factura fiscal de tu compra, mándanos tus datos fiscales \nen la sección de mensajes el mismo dia de la compra, una vez enviado \nel producto no se podrá realizar la factura bajo ninguna excepción\n</pre>\n</html>");
        textoContenido.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelContenidoFondo.add(textoContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 550, -1));

        precioContenido.setBackground(new java.awt.Color(0, 104, 52));
        precioContenido.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        precioContenido.setForeground(new java.awt.Color(255, 255, 255));
        precioContenido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precioContenido.setText("2999,99€");
        panelContenidoFondo.add(precioContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 150, 40));

        botonAdd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonAdd.setForeground(new java.awt.Color(255, 255, 255));
        botonAdd.setText("Añadir a la cesta");
        botonAdd.setBorder(null);
        botonAdd.setOpaque(false);
        botonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddActionPerformed(evt);
            }
        });
        panelContenidoFondo.add(botonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 140, 40));

        scroll2.setViewportView(panelContenidoFondo);

        panelContenido.add(scroll2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 620, 560));

        fondoPantalla.add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 620, 620));

        panelPrecio.setBackground(new java.awt.Color(204, 255, 102));
        panelPrecio.setOpaque(false);

        javax.swing.GroupLayout panelPrecioLayout = new javax.swing.GroupLayout(panelPrecio);
        panelPrecio.setLayout(panelPrecioLayout);
        panelPrecioLayout.setHorizontalGroup(
            panelPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        panelPrecioLayout.setVerticalGroup(
            panelPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        fondoPantalla.add(panelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 620, 0));

        getContentPane().add(fondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equisMouseClicked
        this.dispose();
        if (cerrar)
            System.exit(0);
        
        if (noticias!=null)
            noticias.closeShop();
    }//GEN-LAST:event_equisMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void panelBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMousePressed
        moving = true;
        start = MouseInfo.getPointerInfo().getLocation();
    }//GEN-LAST:event_panelBarraMousePressed

    private void panelBarraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMouseReleased
        moving = false;
    }//GEN-LAST:event_panelBarraMouseReleased

    private void panelBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMouseDragged
        if (!moving)
            return;
        
        Point actual = MouseInfo.getPointerInfo().getLocation();
        Point widow = this.getLocation();
        this.setLocation(widow.x + actual.x - start.x, widow.y + actual.y - start.y);
        start = actual;
    }//GEN-LAST:event_panelBarraMouseDragged

    private void comboOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOrdenActionPerformed
        orderBy = comboOrden.getSelectedIndex();
        mostrarProductosLista();
    }//GEN-LAST:event_comboOrdenActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        busqueda  = buscador.getText();
        orderBy = comboOrden.getSelectedIndex();
        mostrarProductosLista();
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddActionPerformed
        addToCarrito(productSelected);
    }//GEN-LAST:event_botonAddActionPerformed

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarActionPerformed
        FinalizarCompra fin = new FinalizarCompra(this, true, this, productos, monedero);
        fin.setVisible(true);
    }//GEN-LAST:event_botonFinalizarActionPerformed

    public void setMonedero (double d) {
        monedero = d;
        valorMonedero.setText((new DecimalFormat("0.00")).format(monedero)+"€");
        actualizarCarrito();
    }
    
    private void addToCarrito (Producto p) {
        if (productos.containsKey(p)) {
            productos.put(p, productos.get(p)+1);
        } else {
            productos.put(p,1);
        }
        actualizarCarrito();
    }
    
    public void actualizarCarrito () {
        double total = 0;
        for (Map.Entry<Producto, Integer> entry : productos.entrySet()) {
            total += entry.getKey().getPrecio() * entry.getValue();
        }
        valorCarrito.setText((new DecimalFormat("0.00")).format(total)+"€");
        repaint();
    }
    
    private void mostrarProductosLista () {
        busqueda = buscador.getText();
        busqueda = busqueda.equals("Buscar...") ? "" : busqueda; 
        listaProductos = ListaProductos.getNoticias(busqueda, ListaProductos.ORDERBY.values()[orderBy]);
        
        int size = listaProductos.size();
        DecimalFormat format = new DecimalFormat("0.00");
        
        Iterator i = listaProductos.iterator();
        for (JPanel panel: listeners) {
            if (!i.hasNext())
                break;
            
            panel.setVisible(true);
            final Producto p = (Producto) i.next();
            
            // Eliminamos el anterior listener
            MouseListener[] mL = panel.getMouseListeners();
            if (mL.length>0)
                panel.removeMouseListener(mL[0]);
            
            // Añadimos un nuevo Listener
            panel.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    mostrarContenido(p);
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    
                }
            });
            
            // Cambiamos la info
            Component[] componentes = panel.getComponents();
            for (Component c : componentes) {
                
                switch(c.getName()){
                    case "imagen":
                        ((JPanelImage)c).setImagenFondo(new ImagenFondo(new File(p.getImage()), 1f));
                        break;
                    case "titulo":
                        ((JLabel)c).setText("<html>"+p.getNombre()+"</html>");
                        break;
                    case "precio":
                        ((JLabel)c).setText(format.format(p.getPrecio())+"€");
                        break;
                    case "puntuacion":
                        ((JLabel)c).setText("<html>"+getPuntuacion(p.getPuntuacion())+"</html>");
                        break;
                }
            }
        }
        
        // Ocultamos los que no salgan
        for (int j = size; j < listeners.length; j++) {
            listeners[j].setVisible(false);
        }
        
        repaint();
    }
    
    private void mostrarContenido (Producto p) {
        productSelected = p;
        
        img1.setImagenFondo(new ImagenFondo(new File("./imagenes/dummy.png"),1f));
        img2.setImagenFondo(new ImagenFondo(new File("./imagenes/dummy.png"),1f));
        img3.setImagenFondo(new ImagenFondo(new File("./imagenes/dummy.png"),1f));
        
        tituloContenido.setText(p.getNombre());
        textoContenido.setText("<html><p>"+p.getDescripcion()+"</p></html>");
        precioContenido.setText((new DecimalFormat("0.00")).format(p.getPrecio())+"€");
        puntuacionContenido.setText("<html>"+getPuntuacion(p.getPuntuacion())+"</html>");
        
        panelContenidoFondo.setVisible(true);
        
        panelContenidoFondo.setPreferredSize(new Dimension(603, 440+textoContenido.getSize().height));
        repaint();
    }
    
    private void reiniciarContenido () {
        panelContenidoFondo.setVisible(false);
        panelContenidoFondo.setPreferredSize(new Dimension(603, 440));
        repaint();
    }
    
    private String getPuntuacion(int puntos) {
        switch(puntos) {
            case 10:
            case 9:
                return "★★★★★";
            case 8:
            case 7:
                return "★★★★";
            case 6:
            case 5:
                return "★★★";
            case 4:
            case 3:
                return "★★";
            case 2:
            case 1:
                return "★";
        }
        
        return "";
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tienda(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdd;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonFinalizar;
    private javax.swing.JTextField buscador;
    private javax.swing.JLabel categoriaTodas1;
    private javax.swing.JLabel categoriaTodas10;
    private javax.swing.JLabel categoriaTodas11;
    private javax.swing.JLabel categoriaTodas12;
    private javax.swing.JLabel categoriaTodas13;
    private javax.swing.JLabel categoriaTodas14;
    private javax.swing.JLabel categoriaTodas15;
    private javax.swing.JLabel categoriaTodas16;
    private javax.swing.JLabel categoriaTodas17;
    private javax.swing.JLabel categoriaTodas18;
    private javax.swing.JLabel categoriaTodas19;
    private javax.swing.JLabel categoriaTodas20;
    private javax.swing.JLabel categoriaTodas21;
    private javax.swing.JLabel categoriaTodas22;
    private javax.swing.JLabel categoriaTodas23;
    private javax.swing.JLabel categoriaTodas24;
    private javax.swing.JLabel categoriaTodas25;
    private javax.swing.JLabel categoriaTodas6;
    private javax.swing.JLabel categoriaTodas7;
    private javax.swing.JLabel categoriaTodas8;
    private javax.swing.JLabel categoriaTodas9;
    private javax.swing.JComboBox<String> comboOrden;
    private javax.swing.JLabel equis;
    private jpanelimage.JPanelImage fondoPantalla;
    private jpanelimage.JPanelImage iconoCarrito;
    private jpanelimage.JPanelImage iconoCartera;
    private jpanelimage.JPanelImage img1;
    private jpanelimage.JPanelImage img2;
    private jpanelimage.JPanelImage img3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private jpanelimage.JPanelImage jPanelImage10;
    private jpanelimage.JPanelImage jPanelImage11;
    private jpanelimage.JPanelImage jPanelImage12;
    private jpanelimage.JPanelImage jPanelImage13;
    private jpanelimage.JPanelImage jPanelImage14;
    private jpanelimage.JPanelImage jPanelImage15;
    private jpanelimage.JPanelImage jPanelImage6;
    private jpanelimage.JPanelImage jPanelImage7;
    private jpanelimage.JPanelImage jPanelImage8;
    private jpanelimage.JPanelImage jPanelImage9;
    private javax.swing.JLabel minimizar;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JPanel panelBuscador;
    private javax.swing.JPanel panelCategorias;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelContenidoFondo;
    private javax.swing.JPanel panelPrecio;
    private javax.swing.JPanel panelProducto;
    private javax.swing.JLabel precioContenido;
    private javax.swing.JPanel producto1;
    private javax.swing.JPanel producto10;
    private javax.swing.JPanel producto2;
    private javax.swing.JPanel producto3;
    private javax.swing.JPanel producto4;
    private javax.swing.JPanel producto5;
    private javax.swing.JPanel producto6;
    private javax.swing.JPanel producto7;
    private javax.swing.JPanel producto8;
    private javax.swing.JPanel producto9;
    private javax.swing.JLabel puntuacion1;
    private javax.swing.JLabel puntuacion10;
    private javax.swing.JLabel puntuacion2;
    private javax.swing.JLabel puntuacion3;
    private javax.swing.JLabel puntuacion4;
    private javax.swing.JLabel puntuacion5;
    private javax.swing.JLabel puntuacion6;
    private javax.swing.JLabel puntuacion7;
    private javax.swing.JLabel puntuacion8;
    private javax.swing.JLabel puntuacion9;
    private javax.swing.JLabel puntuacionContenido;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JScrollPane scroll2;
    private javax.swing.JLabel textoContenido;
    private javax.swing.JLabel tituloContenido;
    private javax.swing.JLabel valorCarrito;
    private javax.swing.JLabel valorMonedero;
    // End of variables declaration//GEN-END:variables
}