package eltiempo;

import java.awt.Color;
import java.io.File;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import jpanelimage.ImagenFondo;
import jpanelimage.JPanelImage;


/**
 *
 * @author Adrián
 */
public class Principal extends javax.swing.JFrame {

    public enum ESTADO {
        soleado("./imagenes/iconoSoleado.png", "./imagenes/fondoSoleado.jpg"),
        lluvioso("./imagenes/iconoLluvioso.png", "./imagenes/fondoLluvioso.jpg"),
        nublado("./imagenes/iconoNublado.png", "./imagenes/fondoNublado.jpg"),
        ventoso("./imagenes/iconoVentoso.png", "./imagenes/fondoVentoso.jpg");

        String icono;
        String fondo;

        ESTADO(String icono, String fondo) {
            this.icono = icono;
            this.fondo = fondo;
        }

        public String getIcono() {
            return icono;
        }

        public String getFondo() {
            return fondo;
        }
    };

    public enum DIA_SEMANA {
        domingo(0, "Domingo"),
        lunes(1, "Lunes"),
        martes(2, "Martes"),
        miercoles(3, "Miercoles"),
        jueves(4, "Jueves"),
        viernes(5, "Viernes"),
        sabado(6, "Sábado");

        int id;
        String dia;

        DIA_SEMANA(int id, String dia) {
            this.id = id;
            this.dia = dia;
        }

        public int getID() {
            return id;
        }

        public String getDia() {
            return dia;
        }
    };

    // Vamos a configurar bien
    private Dia[] diaSemana;

    // Para el Thread de abrir
    private boolean abierto = true;
    private int state = 0;

    // Para el Thread de noticias/tiempo
    private int tabID = 0;
    private int tabState = 0;

    /**
     * Creates new form Principal
     */
    public Principal() {
        this.setUndecorated(true);
        initComponents();

        imagenIcono.setImagenFondo(new ImagenFondo(new File("iconoLugar.png"), 1f));
        panelDegradado.setImagenFondo(new ImagenFondo(new File("degradado.jpg"), 1f));
        panelNoticias.setImagenFondo(new ImagenFondo(new File("degradado.jpg"), 1f));

        noticia1.setImagenFondo(new ImagenFondo(new File("./imagenes/noticiaT1.jpg"), 1f));
        noticia2.setImagenFondo(new ImagenFondo(new File("./imagenes/noticiaT2.jpg"), 1f));

        diaSemana = new Dia[]{
            new Dia(imgLunes, labelLunes),
            new Dia(imgMartes, labelMartes),
            new Dia(imgMiercoles, labelMiercoles),
            new Dia(imgJueves, labelJueves),
            new Dia(imgViernes, labelViernes),
            new Dia(imgSabado, labelSabado),
            new Dia(imgDomingo, labelDomingo)
        };

        actualizarEstado("Conil, Cádiz", false);

        // Eliminamos la barra
        this.setSize(960, 640);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    private void actualizarEstado(String lugar, boolean toggle) {
        ESTADO[] estados = ESTADO.values();
        int min = 17, max = 20;
        for (Dia d : diaSemana) {
            d.setImg(estados[(int) (Math.round(Math.random() * (estados.length - 1)))]);
            d.setTemperatura((int) Math.round(Math.random() * (max - min) + min));
        }

        Calendar c = Calendar.getInstance();
        DIA_SEMANA[] dias = DIA_SEMANA.values();
        DIA_SEMANA hoy = dias[c.get(Calendar.DAY_OF_WEEK) - 1];
        temperaturaHoy.setText(diaSemana[hoy.getID()].getTemperatura() + "º");
        diaHoy.setText(hoy.getDia() + " " + c.get(Calendar.DAY_OF_MONTH));

        nombreLugar.setText(lugar);

        panelFondo.setImagenFondo(new ImagenFondo(new File(diaSemana[hoy.getID()].getEstado().getFondo()), 1f));

        if (toggle) {
            toggleState();
        }
    }

    private void actualizarEstado(String lugar) {
        actualizarEstado(lugar, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UltimaLocalizacion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bCadiz = new javax.swing.JButton();
        bSanFernando = new javax.swing.JButton();
        bConil = new javax.swing.JButton();
        bPuertoReal = new javax.swing.JButton();
        bMairena = new javax.swing.JButton();
        panelFondo = new jpanelimage.JPanelImage();
        nombreLugar = new javax.swing.JLabel();
        botonNoticia = new javax.swing.JLabel();
        panelLocalizacion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        equisButton = new javax.swing.JLabel();
        botonTiempo = new javax.swing.JLabel();
        barraSeleccion = new javax.swing.JPanel();
        imagenIcono = new jpanelimage.JPanelImage();
        jLabel9 = new javax.swing.JLabel();
        panelDegradado = new jpanelimage.JPanelImage();
        diaHoy = new javax.swing.JLabel();
        temperaturaHoy = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        imgDomingo = new jpanelimage.JPanelImage();
        jLabel10 = new javax.swing.JLabel();
        labelDomingo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        imgLunes = new jpanelimage.JPanelImage();
        jLabel12 = new javax.swing.JLabel();
        labelLunes = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        imgMartes = new jpanelimage.JPanelImage();
        jLabel14 = new javax.swing.JLabel();
        labelMartes = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        imgMiercoles = new jpanelimage.JPanelImage();
        jLabel16 = new javax.swing.JLabel();
        labelMiercoles = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        imgJueves = new jpanelimage.JPanelImage();
        jLabel18 = new javax.swing.JLabel();
        labelJueves = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        imgViernes = new jpanelimage.JPanelImage();
        jLabel20 = new javax.swing.JLabel();
        labelViernes = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        imgSabado = new jpanelimage.JPanelImage();
        jLabel22 = new javax.swing.JLabel();
        labelSabado = new javax.swing.JLabel();
        panelNoticias = new jpanelimage.JPanelImage();
        noticia2 = new jpanelimage.JPanelImage();
        jLabel2 = new javax.swing.JLabel();
        noticia1 = new jpanelimage.JPanelImage();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UltimaLocalizacion.setBackground(new java.awt.Color(51, 51, 51));
        UltimaLocalizacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Últimas localizaciones:");
        UltimaLocalizacion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 40));

        bCadiz.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        bCadiz.setText("Cádiz, Cádiz");
        bCadiz.setFocusable(false);
        bCadiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadizActionPerformed(evt);
            }
        });
        UltimaLocalizacion.add(bCadiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 30));

        bSanFernando.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        bSanFernando.setText("San Fernando, Cádiz");
        bSanFernando.setFocusable(false);
        bSanFernando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSanFernandoActionPerformed(evt);
            }
        });
        UltimaLocalizacion.add(bSanFernando, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 170, 30));

        bConil.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        bConil.setText("Conil, Cádiz");
        bConil.setFocusable(false);
        bConil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConilActionPerformed(evt);
            }
        });
        UltimaLocalizacion.add(bConil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, 30));

        bPuertoReal.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        bPuertoReal.setText("Puerto Real, Cádiz");
        bPuertoReal.setFocusable(false);
        bPuertoReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPuertoRealActionPerformed(evt);
            }
        });
        UltimaLocalizacion.add(bPuertoReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 170, 30));

        bMairena.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        bMairena.setText("Mairena de Aljarafe, Sevilla");
        bMairena.setFocusable(false);
        bMairena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMairenaActionPerformed(evt);
            }
        });
        UltimaLocalizacion.add(bMairena, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 170, 30));

        getContentPane().add(UltimaLocalizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 0, 240, 420));

        panelFondo.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("/home/alumno"), 0.5f));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreLugar.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        nombreLugar.setForeground(new java.awt.Color(255, 255, 255));
        nombreLugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreLugar.setText("Conil, Cádiz");
        panelFondo.add(nombreLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, 150, 30));

        botonNoticia.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        botonNoticia.setForeground(new java.awt.Color(255, 255, 255));
        botonNoticia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonNoticia.setText("NOTICIAS");
        botonNoticia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNoticiaMouseClicked(evt);
            }
        });
        panelFondo.add(botonNoticia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, -1, 40));

        panelLocalizacion.setBackground(new java.awt.Color(0, 153, 102));
        panelLocalizacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Últimas localizaciones");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        panelLocalizacion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 50));

        panelFondo.add(panelLocalizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 240, 50));

        equisButton.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        equisButton.setForeground(new java.awt.Color(255, 255, 255));
        equisButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equisButton.setText("x");
        equisButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equisButtonMouseClicked(evt);
            }
        });
        panelFondo.add(equisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 170, 30, 30));

        botonTiempo.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        botonTiempo.setForeground(new java.awt.Color(255, 255, 255));
        botonTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonTiempo.setText("TIEMPO ");
        botonTiempo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTiempoMouseClicked(evt);
            }
        });
        panelFondo.add(botonTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, 40));

        barraSeleccion.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.add(barraSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 585, 70, 5));

        imagenIcono.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("/home/alumno"), 0.5f));
        panelFondo.add(imagenIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 70, 80));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ElTiempoAPP");
        panelFondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 50));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -170, 960, 590));

        panelDegradado.setForeground(new java.awt.Color(255, 255, 255));
        panelDegradado.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("/home/alumno"), 0.5f));
        panelDegradado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diaHoy.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        diaHoy.setForeground(new java.awt.Color(255, 255, 255));
        diaHoy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diaHoy.setText("Sábado 22");
        panelDegradado.add(diaHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 20));

        temperaturaHoy.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        temperaturaHoy.setForeground(new java.awt.Color(255, 255, 255));
        temperaturaHoy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temperaturaHoy.setText("21º");
        panelDegradado.add(temperaturaHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, 70));
        panelDegradado.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 1, 170));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgDomingo.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("/home/alumno"), 0.5f));
        jPanel6.add(imgDomingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 70));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Sábado");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        labelDomingo.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        labelDomingo.setForeground(new java.awt.Color(255, 255, 255));
        labelDomingo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDomingo.setText("21º");
        jPanel6.add(labelDomingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 90, 30));

        panelDegradado.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 90, 130));

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLunes.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("/home/alumno"), 0.5f));
        jPanel7.add(imgLunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 70));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Domingo");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        labelLunes.setBackground(new java.awt.Color(255, 26, 246));
        labelLunes.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        labelLunes.setForeground(new java.awt.Color(255, 255, 255));
        labelLunes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLunes.setText("21º");
        jPanel7.add(labelLunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 90, 30));

        panelDegradado.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 90, 130));

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgMartes.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("/home/alumno"), 0.5f));
        jPanel8.add(imgMartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 70));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Lunes");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        labelMartes.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        labelMartes.setForeground(new java.awt.Color(255, 255, 255));
        labelMartes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMartes.setText("21º");
        jPanel8.add(labelMartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 90, 30));

        panelDegradado.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 90, 130));

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgMiercoles.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("/home/alumno"), 0.5f));
        jPanel9.add(imgMiercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 70));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Martes");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        labelMiercoles.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        labelMiercoles.setForeground(new java.awt.Color(255, 255, 255));
        labelMiercoles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMiercoles.setText("21º");
        jPanel9.add(labelMiercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 90, 30));

        panelDegradado.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 90, 130));

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgJueves.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("/home/alumno"), 0.5f));
        jPanel10.add(imgJueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 70));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Miercoles");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        labelJueves.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        labelJueves.setForeground(new java.awt.Color(255, 255, 255));
        labelJueves.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJueves.setText("21º");
        jPanel10.add(labelJueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 90, 30));

        panelDegradado.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 90, 130));

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgViernes.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("/home/alumno"), 0.5f));
        jPanel11.add(imgViernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 70));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Jueves");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        labelViernes.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        labelViernes.setForeground(new java.awt.Color(255, 255, 255));
        labelViernes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelViernes.setText("21º");
        jPanel11.add(labelViernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 90, 30));

        panelDegradado.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 90, 130));

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgSabado.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("/home/alumno"), 0.5f));
        jPanel12.add(imgSabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 70));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Viernes");
        jPanel12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        labelSabado.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        labelSabado.setForeground(new java.awt.Color(255, 255, 255));
        labelSabado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSabado.setText("21º");
        jPanel12.add(labelSabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 90, 30));

        panelDegradado.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 90, 130));

        getContentPane().add(panelDegradado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 960, 230));

        panelNoticias.setForeground(new java.awt.Color(255, 255, 255));
        panelNoticias.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("/home/alumno"), 0.5f));
        panelNoticias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noticia2.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("/home/alumno"), 0.5f));
        noticia2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("San fernando despide 2018 a lo grande");
        jLabel2.setOpaque(true);
        noticia2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 370, 30));

        panelNoticias.add(noticia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 400, 190));

        noticia1.setImagenFondo(new jpanelimage.ImagenFondo(new java.io.File("/home/alumno"), 0.5f));
        noticia1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Que ver si pasas las vacaciones en Conil");
        jLabel5.setOpaque(true);
        noticia1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 370, 30));

        panelNoticias.add(noticia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 400, 190));

        getContentPane().add(panelNoticias, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 410, 960, 230));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 960, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equisButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equisButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_equisButtonMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        toggleState();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void bMairenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMairenaActionPerformed
        actualizarEstado("Mairena de Aljarafe, Sevilla");
    }//GEN-LAST:event_bMairenaActionPerformed

    private void bCadizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadizActionPerformed
        actualizarEstado("Cádiz, Cádiz");
    }//GEN-LAST:event_bCadizActionPerformed

    private void bSanFernandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSanFernandoActionPerformed
        actualizarEstado("San Fernando, Cádiz");
    }//GEN-LAST:event_bSanFernandoActionPerformed

    private void bConilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConilActionPerformed
        actualizarEstado("Conil, Cádiz");
    }//GEN-LAST:event_bConilActionPerformed

    private void bPuertoRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPuertoRealActionPerformed
        actualizarEstado("Puerto Real, Cádiz");
    }//GEN-LAST:event_bPuertoRealActionPerformed

    private void botonTiempoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTiempoMouseClicked
        changeTab(0);
    }//GEN-LAST:event_botonTiempoMouseClicked

    private void botonNoticiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNoticiaMouseClicked
        changeTab(1);
    }//GEN-LAST:event_botonNoticiaMouseClicked

    private void toggleState() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                int posActual = UltimaLocalizacion.getLocation().x;
                int posFinal = (abierto) ? 0 : -240;
                abierto = !abierto;
                state++;
                int _state = state;

                int dif = posFinal - posActual;

                double lerp = 0;
                double deltaTime = 0.01;
                double velocidad = 10;

                while (lerp < 1) {
                    if (state != _state) {
                        break;
                    }
                    UltimaLocalizacion.setLocation(
                            (int) (posActual + (dif * lerp)), 0);
                    try {
                        Thread.sleep(10);
                    } catch (InterruptedException ex) {
                        System.err.println("Error interrumpido: " + ex.getMessage());
                    }
                    lerp += deltaTime * velocidad;
                }
            }
        }).start();
    }

    private void changeTab(int tabId) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                if (tabID == tabId) {
                    return;
                }

                tabID = tabId;
                tabState++;
                int _state = tabState;

                int _y = panelDegradado.getLocation().y;
                //Inicio
                int xIDegradado = panelDegradado.getLocation().x;
                int xINoticias = panelNoticias.getLocation().x;
                int xIBarrita = barraSeleccion.getLocation().x;

                //Final
                int xFDegradado = tabID == 0 ? 0 : -960;
                int xFNoticias = tabID == 0 ? 960 : 0;
                int xFBarrita = tabID == 0 ? 20 : 110;

                double lerp = 0;
                double deltaTime = 0.01;
                double velocidad = 20;

                while (lerp < 1) {
                    if (tabState != _state) {
                        break;
                    }

                    panelDegradado.setLocation((int) (xIDegradado + ((xFDegradado - xIDegradado) * lerp)), _y);
                    panelNoticias.setLocation((int) (xINoticias + ((xFNoticias - xINoticias) * lerp)), _y);
                    barraSeleccion.setLocation((int) (xIBarrita + ((xFBarrita - xIBarrita) * lerp)), 585);

                    try {
                        Thread.sleep(10);
                    } catch (InterruptedException ex) {
                        System.err.println("Error interrumpido: " + ex.getMessage());
                    }
                    lerp += deltaTime * velocidad;
                }

                panelDegradado.setLocation(xFDegradado, _y);
                panelNoticias.setLocation(xFNoticias, _y);
                barraSeleccion.setLocation(xFBarrita, 585);
            }
        }).start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UltimaLocalizacion;
    private javax.swing.JButton bCadiz;
    private javax.swing.JButton bConil;
    private javax.swing.JButton bMairena;
    private javax.swing.JButton bPuertoReal;
    private javax.swing.JButton bSanFernando;
    private javax.swing.JPanel barraSeleccion;
    private javax.swing.JLabel botonNoticia;
    private javax.swing.JLabel botonTiempo;
    private javax.swing.JLabel diaHoy;
    private javax.swing.JLabel equisButton;
    private jpanelimage.JPanelImage imagenIcono;
    private jpanelimage.JPanelImage imgDomingo;
    private jpanelimage.JPanelImage imgJueves;
    private jpanelimage.JPanelImage imgLunes;
    private jpanelimage.JPanelImage imgMartes;
    private jpanelimage.JPanelImage imgMiercoles;
    private jpanelimage.JPanelImage imgSabado;
    private jpanelimage.JPanelImage imgViernes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelDomingo;
    private javax.swing.JLabel labelJueves;
    private javax.swing.JLabel labelLunes;
    private javax.swing.JLabel labelMartes;
    private javax.swing.JLabel labelMiercoles;
    private javax.swing.JLabel labelSabado;
    private javax.swing.JLabel labelViernes;
    private javax.swing.JLabel nombreLugar;
    private jpanelimage.JPanelImage noticia1;
    private jpanelimage.JPanelImage noticia2;
    private jpanelimage.JPanelImage panelDegradado;
    private jpanelimage.JPanelImage panelFondo;
    private javax.swing.JPanel panelLocalizacion;
    private jpanelimage.JPanelImage panelNoticias;
    private javax.swing.JLabel temperaturaHoy;
    // End of variables declaration//GEN-END:variables

}
